apiVersion: v2
name: mishmarot
description: Global Antisemitism Situational Awareness Dashboard
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: redis
    version: "~19.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
