apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mishmarot.fullname" . }}-app
  labels:
    {{- include "mishmarot.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: {{ include "mishmarot.fullname" . }}-app-secrets
            - configMapRef:
                name: {{ include "mishmarot.fullname" . }}-app-config
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
