apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mishmarot.fullname" . }}-app-config
data:
  NEXT_PUBLIC_SUPABASE_URL: {{ .Values.supabase.url | quote }}
  REDIS_URL: "redis://:$(REDIS_PASSWORD)@{{ include "mishmarot.fullname" . }}-redis-master:6379"
