import { db } from "./index.js";
import { incidents, dataSources } from "./schema/index.js";
import { eq } from "drizzle-orm";

const SEED_SOURCE_ID = "seed";

const SEED_INCIDENTS: (typeof incidents.$inferInsert)[] = [
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-001",
    occurredAt: daysAgo(1),
    timePrecision: 2,
    lat: 40.7128,
    lon: -74.006,
    geoPrecision: 3,
    countryIso: "US",
    admin1: "New York",
    locality: "New York City",
    incidentType: "abusive_behaviour",
    severity: 5,
    setting: "street_public_space",
    manifestations: ["othering"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Antisemitic slurs directed at visibly Jewish pedestrian in Midtown Manhattan",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-002",
    occurredAt: daysAgo(2),
    timePrecision: 2,
    lat: 51.5074,
    lon: -0.1278,
    geoPrecision: 3,
    countryIso: "GB",
    admin1: "England",
    locality: "London",
    incidentType: "targeted_damage",
    severity: 3,
    setting: "synagogue_jewish_institution",
    manifestations: ["modern"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Windows smashed at synagogue, antisemitic graffiti sprayed on exterior wall",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-003",
    occurredAt: daysAgo(3),
    timePrecision: 2,
    lat: 48.8566,
    lon: 2.3522,
    geoPrecision: 3,
    countryIso: "FR",
    admin1: "Île-de-France",
    locality: "Paris",
    incidentType: "assault",
    severity: 2,
    setting: "street_public_space",
    manifestations: ["israel_related"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Physical assault on man wearing Star of David necklace near Marais district",
    sourceUrl: null,
    gdprReviewRequired: true,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-004",
    occurredAt: daysAgo(4),
    timePrecision: 2,
    lat: 52.52,
    lon: 13.405,
    geoPrecision: 3,
    countryIso: "DE",
    admin1: "Berlin",
    locality: "Berlin",
    incidentType: "desecration",
    severity: 3,
    setting: "cemetery_memorial",
    manifestations: ["post_shoah"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Holocaust memorial vandalized with swastika graffiti",
    sourceUrl: null,
    gdprReviewRequired: true,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-005",
    occurredAt: daysAgo(5),
    timePrecision: 2,
    lat: 34.0522,
    lon: -118.2437,
    geoPrecision: 3,
    countryIso: "US",
    admin1: "California",
    locality: "Los Angeles",
    incidentType: "online_abuse",
    severity: 5,
    setting: "online",
    manifestations: ["modern", "othering"],
    explicitness: "coded",
    confidence: 2,
    summary: "[SEED] Coordinated antisemitic harassment campaign targeting Jewish community organization's social media accounts",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-006",
    occurredAt: daysAgo(6),
    timePrecision: 2,
    lat: 32.0853,
    lon: 34.7818,
    geoPrecision: 3,
    countryIso: "IL",
    admin1: "Tel Aviv",
    locality: "Tel Aviv",
    incidentType: "threat",
    severity: 4,
    setting: "campus",
    manifestations: ["israel_related"],
    explicitness: "implicit",
    confidence: 2,
    summary: "[SEED] Threatening messages sent to Jewish student association at university campus",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-007",
    occurredAt: daysAgo(8),
    timePrecision: 2,
    lat: 41.9028,
    lon: 12.4964,
    geoPrecision: 3,
    countryIso: "IT",
    admin1: "Lazio",
    locality: "Rome",
    incidentType: "propaganda_literature",
    severity: 5,
    setting: "street_public_space",
    manifestations: ["post_shoah", "modern"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Antisemitic flyers with conspiracy theories distributed in Jewish quarter",
    sourceUrl: null,
    gdprReviewRequired: true,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-008",
    occurredAt: daysAgo(10),
    timePrecision: 2,
    lat: 45.4215,
    lon: -75.6972,
    geoPrecision: 3,
    countryIso: "CA",
    admin1: "Ontario",
    locality: "Ottawa",
    incidentType: "targeted_damage",
    severity: 3,
    setting: "residence",
    manifestations: ["othering"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Mezuzah torn from doorpost and swastika carved into front door of Jewish family home",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-009",
    occurredAt: daysAgo(12),
    timePrecision: 2,
    lat: -33.8688,
    lon: 151.2093,
    geoPrecision: 3,
    countryIso: "AU",
    admin1: "New South Wales",
    locality: "Sydney",
    incidentType: "abusive_behaviour",
    severity: 5,
    setting: "workplace",
    manifestations: ["modern"],
    explicitness: "implicit",
    confidence: 2,
    summary: "[SEED] Antisemitic comments and conspiracy theories directed at Jewish colleague in workplace",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-010",
    occurredAt: daysAgo(14),
    timePrecision: 2,
    lat: 59.3293,
    lon: 18.0686,
    geoPrecision: 3,
    countryIso: "SE",
    admin1: "Stockholm",
    locality: "Stockholm",
    incidentType: "institutional",
    severity: 5,
    setting: "government_political",
    manifestations: ["israel_related"],
    explicitness: "ambiguous",
    confidence: 2,
    summary: "[SEED] Municipal council member makes statements applying double standards to Jewish state",
    sourceUrl: null,
    gdprReviewRequired: true,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-011",
    occurredAt: daysAgo(16),
    timePrecision: 2,
    lat: 42.3601,
    lon: -71.0589,
    geoPrecision: 3,
    countryIso: "US",
    admin1: "Massachusetts",
    locality: "Boston",
    incidentType: "threat",
    severity: 4,
    setting: "campus",
    manifestations: ["othering", "modern"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Bomb threat phoned in to Hillel center at university campus",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-012",
    occurredAt: daysAgo(18),
    timePrecision: 2,
    lat: 50.0755,
    lon: 14.4378,
    geoPrecision: 3,
    countryIso: "CZ",
    admin1: "Prague",
    locality: "Prague",
    incidentType: "desecration",
    severity: 3,
    setting: "cemetery_memorial",
    manifestations: ["post_shoah"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Headstones toppled and defaced at historic Jewish cemetery",
    sourceUrl: null,
    gdprReviewRequired: true,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-013",
    occurredAt: daysAgo(20),
    timePrecision: 2,
    lat: 47.3769,
    lon: 8.5417,
    geoPrecision: 3,
    countryIso: "CH",
    admin1: "Zürich",
    locality: "Zürich",
    incidentType: "assault",
    severity: 2,
    setting: "transit",
    manifestations: ["religious"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Orthodox Jewish man attacked on public transit, kippa pulled off",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-014",
    occurredAt: daysAgo(22),
    timePrecision: 2,
    lat: 55.6761,
    lon: 12.5683,
    geoPrecision: 3,
    countryIso: "DK",
    admin1: "Capital Region",
    locality: "Copenhagen",
    incidentType: "targeted_damage",
    severity: 3,
    setting: "synagogue_jewish_institution",
    manifestations: ["israel_related"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Jewish community center windows broken, anti-Israel slogans painted on walls",
    sourceUrl: null,
    gdprReviewRequired: true,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-015",
    occurredAt: daysAgo(25),
    timePrecision: 2,
    lat: 43.6532,
    lon: -79.3832,
    geoPrecision: 3,
    countryIso: "CA",
    admin1: "Ontario",
    locality: "Toronto",
    incidentType: "abusive_behaviour",
    severity: 5,
    setting: "school_k12",
    manifestations: ["othering", "post_shoah"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Jewish student subjected to repeated antisemitic bullying including Holocaust jokes",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
  {
    sourceId: SEED_SOURCE_ID,
    sourceRef: "seed-016",
    occurredAt: daysAgo(28),
    timePrecision: 2,
    lat: -34.6037,
    lon: -58.3816,
    geoPrecision: 3,
    countryIso: "AR",
    admin1: "Buenos Aires",
    locality: "Buenos Aires",
    incidentType: "extreme_violence",
    severity: 1,
    setting: "synagogue_jewish_institution",
    manifestations: ["modern", "religious"],
    explicitness: "explicit",
    confidence: 2,
    summary: "[SEED] Arson attack on synagogue during services, multiple injuries reported",
    sourceUrl: null,
    gdprReviewRequired: false,
  },
];

function daysAgo(n: number): Date {
  return new Date(Date.now() - n * 24 * 60 * 60 * 1000);
}

async function seed() {
  console.log("Seeding database...");

  // Upsert the seed data source
  await db
    .insert(dataSources)
    .values({
      id: SEED_SOURCE_ID,
      name: "Seed Data",
      description: "Synthetic test data — not real incidents",
      isEnabled: false,
      incidentCount: 0,
    })
    .onConflictDoNothing();

  // Clear previous seed incidents
  await db.delete(incidents).where(eq(incidents.sourceId, SEED_SOURCE_ID));

  // Insert seed incidents
  const inserted = await db
    .insert(incidents)
    .values(SEED_INCIDENTS)
    .returning({ id: incidents.id });

  // Update count on data source
  await db
    .update(dataSources)
    .set({ incidentCount: inserted.length })
    .where(eq(dataSources.id, SEED_SOURCE_ID));

  console.log(`Seeded ${inserted.length} incidents with source_id="${SEED_SOURCE_ID}"`);
  console.log("All summaries are prefixed with [SEED] for visibility.");
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
